# Build stage
FROM golang:1.20.7-alpine3.17
# Set the current working directory inside the container
WORKDIR /app
# Copy the source from the current directory to the working Directory inside the container
COPY ./app .
# COPY ./app/config-files/dev.json ./config.json
# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download
RUN go install github.com/githubnemo/CompileDaemon@latest
# Hot-reload entrypoint
ENTRYPOINT CompileDaemon --build="go build main.go" --command=./main
